<div class="homepage-presentation">
    <div class="description1">
        <div class="column" style="text-align: center; font-family: "Helvetica Neue"; font-size: 13pt;">
            <h2><strong>Cele mai subțiri huse care arată și bine</strong></h2>
            <p>Rareori cineva observă husele noastre. Asta pentru că sunt unele din cele mai subțiri huse create
                vreodată. Se mulează perfect pe curburile telefonului, oferind totodată o protecție completă
                împotriva șocurilor și zgârieturilor.</p>
        </div>
    </div>

    <div class="image1" style="text-align: center;">
        <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/1.jpg" id="logo-footer" alt="" />
    </div>

    <div class="image2" style="text-align: center;">
        <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/1.jpg" id="logo-footer" alt="" />
    </div>

    <div class="description2" style="text-align: center;">
        <div class="column" style="text-align: center; font-family: "Helvetica Neue"; font-size: 13pt;">
            <h2><strong>Design minimalist</strong></h2>
            <p>Fiind concepute dintr-un material flexibil și foarte subțire, decupat în jurul butoanelor, fiecare
                curbură este acoperită perfect, pentru a putea oferi în continuare o experiență unică. Astfel,
                telefonul nu își pierde design-ul elegant, subțire și autentic.</p>
        </div>
    </div>

    <div class="description3">
        <div class="column" style="text-align: center; font-family: "Helvetica Neue"; font-size: 13pt;">
            <h2><strong>Protecție maximă</strong></h2>
            <p>Deși husele sunt de o grosime aproximativ egală cu o coală de hârtie obișnuită, acestea sunt create
                dintr-un material extrem de rezistent care protejează telefonul împotriva zgârieturilor și
                șocurilor.</p>
        </div>
    </div>
    <div class="image3" style="text-align: center;">
        <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/1.jpg" id="logo-footer" alt="" />
    </div>
</div>
