Vagrant.configure("2") do |config|

  config.vm.define "droplet1" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'casacuhuse'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        override.nfs.functional = false
        provider.token = '0217873407c9ab0de210208f505f9d8f3db8b2378c65a5f5d30e4deb41823c2b'
        provider.image = 'ubuntu-16-04-x64'
        provider.region = 'fra1'
        provider.size = '2gb'
      end
  end

  config.ssh.forward_agent = true
  config.vm.synced_folder(".", "/production", disabled: true)

  config.puppet_install.puppet_version = :latest
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = '../puppet/manifests'
    puppet.module_path = '../puppet/modules'
    puppet.manifest_file = 'init-production.pp'
  end

  config.vm.provision "shell", name: "Release", keep_color: true, inline: "
    rm -rf /release
    mkdir -p /var/www/release
    cd /var/www/release
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    git clone git@github.com:PaulPopa/house-of-cases.git
    cd house-of-cases/magento
    composer install
    php bin/magento setup:install --db-host=localhost --db-name=casacuhuse --db-user=casacuhuse --db-password='9Ue61hv7$9eh' --admin-firstname=Admin --admin-lastname=User --admin-email=pxp420mail@gmail.com --admin-user=admin --admin-password='house0fcases' --backend-frontname=admin_hoc
    php bin/magento setup:store-config:set --base-url=http://houseofcases.co.uk/
    php bin/magento module:enable --all
    php bin/magento cache:enable
    php bin/magento cache:disable full_page
    php bin/magento cache:flush
    php bin/magento cache:clean
    php bin/magento setup:upgrade
    php bin/magento deploy:mode:set developer
    bash ../scripts/set-permissions.sh
    cd /var/www/
    rm -rf media/
    cp -rf house-of-cases/magento/pub/media/ media
    rm -rf backup/
    mv house-of-cases/ backup
    mv release/house-of-cases/ house-of-cases
    rm -rf house-of-cases/magento/pub/media/
    cp -rf media/ house-of-cases/magento/pub/media
    cd /var/www/house-of-cases/magento/
    php bin/magento cache:flush
    php bin/magento cache:clean
    bash ../scripts/set-permissions.sh www-data www-data
  "
end
