Vagrant.configure("2") do |config|

  config.vm.define "droplet1" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '~/.ssh/id_rsa'
        override.vm.box = 'casacuhuse'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        override.nfs.functional = false
        provider.token = '0217873407c9ab0de210208f505f9d8f3db8b2378c65a5f5d30e4deb41823c2b'
        provider.image = 'ubuntu-16-04-x64'
        provider.region = 'fra1'
        provider.size = '2gb'
      end
  end

  config.vm.synced_folder(".", "/production", disabled: true)
  config.vm.synced_folder("../../magento/", "/var/www/house-of-cases/magento", owner: "www-data", group: "www-data")
  config.vm.synced_folder("../../scripts/", "/var/www/house-of-cases/scripts", owner: "www-data", group: "www-data")

  config.puppet_install.puppet_version = :latest
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = '../puppet/manifests'
    puppet.module_path = '../puppet/modules'
    puppet.manifest_file = 'init-production.pp'
  end

  config.vm.provision "shell", name: "Magento Setup", keep_color: true, inline: "
    cd /var/www/house-of-cases/magento
    composer install
    php bin/magento setup:install --db-host=localhost --db-name=hoc_dev --db-user=hoc_dev --db-password='n2@79Bn628T7' --admin-firstname=Admin --admin-lastname=User --admin-email=pxp420mail@gmail.com --admin-user=admin --admin-password='house0fcases' --backend-frontname=admin_hoc
    php bin/magento setup:store-config:set --base-url=http://dev-houseofcases.co.uk/
    php bin/magento module:enable --all
    php bin/magento cache:enable
    php bin/magento cache:disable full_page
    php bin/magento cache:flush
    php bin/magento cache:clean
    php bin/magento setup:upgrade
    php bin/magento deploy:mode:set developer
  "

  config.vm.provision "shell", name: "Magerun Install", keep_color: true, inline: "
    cd /var/www/house-of-cases/magento
    wget https://files.magerun.net/n98-magerun2.phar
    chmod +x ./n98-magerun2.phar
    mv ./n98-magerun2.phar /usr/local/bin/
    echo 'alias magerun=\"n98-magerun2.phar\"' >> ~/.bashrc
  "

  config.vm.provision "shell", name: "Run Scripts", keep_color: true, inline: "
    cd /var/www/house-of-cases/magento
    bash ../scripts/set-permissions.sh
  "
end
