<ul class="navigation-bar">
    <div class="dropdown">
        <li class="dropbtn"><a>Produse</a>
            <i class="fa fa-caret-down" style="color:black;"></i>
        </li>
        <div class="dropdown-content">
            <a href="https://google.com/">iPhone X</a>
            <a href="https://google.com/">iPhone 8 Plus</a>
            <a href="https://google.com/">iPhone 8</a>
            <a href="https://google.com/">iPhone 7 Plus</a>
            <a href="https://google.com/">iPhone 7</a>
        </div>
    </div>
    <li><a>Despre Noi</a></li>
    <li><a>FAQ</a></li>
    <li><a>Contact</a></li>
</ul>