<title></title>
<div class="product-description">
<div class="pp-half-blocks js-half-blocks" style="box-sizing: border-box; font-family: Lato, sans-
serif; font-size: 14px;">
    <div class="half-block half-block--image" style="box-sizing: border-box; text-align: center; display: flex; -webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-flow: row nowrap; border: none;">
        <div class="half-block__item half-block__item--even half-block__item--bg js-block-bg" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-
flow: row wrap; min-height: 1px; background-size: cover; background-position: 50% 50%; background-repeat: no-repeat; -webkit-box-ordinal-group: 2; order: 1; background-image: url('//cdn.shopify.com/s/files/1/1166/1584/products/cool-thin-iphone-x-case-white.jpg?

v=1524180653');"><img class="half-block__image js-
block-img" style="box-sizing: border-box; max-width: 100%; border: 0px; display: block; width: 686px; visibility: hidden; opacity: 0;" src="https://cdn.shopify.com/s/files/1/1166/1584/products/cool-thin-iphone-x-case-
white.jpg?v=1524180653" alt="cool white iPhone X case" /></div>
        <div class="half-block__item" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -webkit-box-orient: horizontal; -
webkit-box-direction: normal; flex-flow: row wrap; min-height: 1px;">
            <div class="half-block__desc" style="box-sizing: border-box; padding: 55px; max-width: 520px; margin: 0px auto;">
                <h2 dir="ltr" style="line-height: 1.38; margin-top: 18pt; margin-bottom: 4pt;"><span id="docs-
internal-guid-30dc8187-1654-4e99-59f9-5af932411e04"><span style="font-size: 17pt; font-
family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-variant-
numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-
wrap;">Aproape la fel de subțire ca o coală de hârtie.</span></span></h2>
                <p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span id="docs-internal-
guid-30dc8187-1654-4e99-59f9-5af932411e04"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-
east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Husa este destul de groasă încât să îți protejeze telefonul de șocuri și zgârieturi în totalitate, dar îndeajuns de subțire încât telefonul tău să își păstreze aspectul original, slim și elegant.</span></span></p>
                <div> </div>
            </div>
        </div>
    </div>
    <div class="half-block half-block--image" style="box-sizing: border-box; text-align: center; display: flex; -webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-flow: row nowrap; border: none;">
        <div class="half-block__item half-block__item--bg js-block-bg" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -
webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-flow: row wrap; min-height: 1px; background-size: cover; background-position: 50% 50%; background-repeat: no-repeat; background-image: url('//cdn.shopify.com/s/files/1/1166/1584/products/thinnest-white-
iphone-x-case.jpg?v=1524180641');"><img class="half-
block__image js-block-img" style="box-sizing: border-box; max-width: 100%; border: 0px; display: block; width: 686px; visibility: hidden; opacity: 0;" src="https://cdn.shopify.com/s/files/1/1166/1584/products/thinnest-

white-iphone-x-case.jpg?v=1524180641" alt="thin white iPhone X case" /></div>
        <div class="half-block__item" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -webkit-box-orient: horizontal; -
webkit-box-direction: normal; flex-flow: row wrap; min-height: 1px;">
            <div class="half-block__desc" style="box-sizing: border-box; padding: 55px; max-width: 520px; margin: 0px auto;">
                <h2 dir="ltr" style="line-height: 1.38; margin-top: 18pt; margin-bottom: 4pt;"><span id="docs-
internal-guid-955634b5-1654-7da3-89aa-194b7d36587d"><span style="font-size: 17pt; font-
family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-variant-
numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: pre-
wrap;">Rezistentă chiar și împotriva șocurilor puternice și repetate.</span></span></h2>
                <p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span id="docs-internal-
guid-955634b5-1654-7da3-89aa-194b7d36587d"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-variant-numeric: normal; font-
variant-east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Husa este creată din polipropilenă, un material dur, care rezistă chiar și șocurilor repetate. Astfel, telefonul tău este în deplină siguranță și nu va trebui să îți faci griji chiar dacă a suferit accidente repetate.</span></span></p>
                <div> </div>
            </div>
        </div>
    </div>
    <div class="half-block half-block--image" style="box-sizing: border-box; text-align: center; display: flex; -webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-flow: row nowrap; border: none;">
        <div class="half-block__item half-block__item--even half-block__item--bg js-block-bg" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -webkit-box-orient: horizontal; -webkit-box-direction: normal; flex-
flow: row wrap; min-height: 1px; background-size: cover; background-position: 50% 50%; background-repeat: no-repeat; -webkit-box-ordinal-group: 2; order: 1; background-image: url('//cdn.shopify.com/s/files/1/1166/1584/files/best-thin-iPhone-X-cases.jpg?

v=1522447505');"><img class="half-
block__image js-block-img" style="box-sizing: border-box; max-width: 100%; border: 0px; display: block; width: 686px; visibility: hidden; opacity: 0;" src="https://cdn.shopify.com/s/files/1/1166/1584/files/best-thin-
iPhone-X-cases.jpg?v=1522447505" alt="3 finishes.&lt;br&gt;1 great iPhone case." /></div>
        <div class="half-block__item" style="box-sizing: border-box; width: 686px; flex-basis: 50%; display: flex; -webkit-box-align: center; align-items: center; -webkit-box-orient: horizontal; -
webkit-box-direction: normal; flex-flow: row wrap; min-height: 1px;">
            <div class="half-block__desc" style="box-sizing: border-box; padding: 55px; max-width: 520px; margin: 0px auto;">
                <h2 dir="ltr" style="line-height: 1.38; margin-top: 18pt; margin-bottom: 4pt;"><span id="docs-
internal-guid-c38651a5-1654-a75e-73f9-54625e868a89"><span style="font-size: 17pt; font-
family: Arial; color: #000000; background-color: transparent; font-weight: bold; font-variant-
numeric: normal; font-variant-east-asian: normal; vertical-align: baseline; white-space: nowrap;">Ca și nouă - chiar și după 2 ani de utilizare.</span></span></h2>
                <p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span id="docs-internal-
guid-c38651a5-1654-a75e-73f9-54625e868a89"><span style="font-size: 11pt; font-family: Arial; color: #000000; background-color: transparent; font-variant-numeric: normal; font-variant-
east-asian: normal; vertical-align: baseline; white-space: pre-wrap;">Majoritatea huselor își schimbă culoarea după doar câteva zile de utilizare. Carcasele noastre însă sunt create dintr-un material special care nu se îngălbenește odată cu trecerea timpului și își păstrează aceeași frumusețe din prima zi, chiar și după un timp îndelungat de folosire.  </span></span></p>
                <div> </div>
            </div>
        </div>
    </div>
</div>
</div>