<div class="footer-logo">
    <img src="http://houseofcases.co.uk/pub/media/logo/stores/footer.png" id="logo-footer" alt="" />
</div>
<div class="footer-left">
    <li><a href="http://houseofcases.co.uk/termeni">Termeni si conditii</a></li>
    <li><a href="http://houseofcases.co.uk/confidentialitate">Politica de confidentialitate</a></li>
    <li><a href="http://houseofcases.co.uk/enable-cookies">Politica de utilizare cookies</a></li>
</div>

<div class="footer-right">
    <li><a href="http://houseofcases.co.uk/iphone-x-case">FAQ</a></li>
    <li><a href="http://houseofcases.co.uk/iphone-x-case">SOL</a></li>
    <li><a href="http://houseofcases.co.uk/iphone-x-case">ANPC</a></li>
</div>

<div class="social-links">
    <li>
        <a href="https://www.facebook.com/casacuhuse.ro/" >
         <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/facebook.png" />
        </a>
    </li>

    <li>
        <a href="http://instagram.com/" >
            <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/instagram.png" />
        </a>
    </li>
</div>

