<div class="footer-logo">
    <img src="http://dev-houseofcases.co.uk/pub/media/logo/stores/footer.png" id="logo-footer" alt="" />
</div>
<div class="footer-left">
    <li><a href="http://dev-houseofcases.co.uk/termeni">Termeni si conditii</a></li>
    <li><a href="http://dev-houseofcases.co.uk/confidentialitate">Politica de confidentialitate</a></li>
    <li><a href="http://dev-houseofcases.co.uk/enable-cookies">Politica de utilizare cookies</a></li>
</div>

<div class="footer-right">
    <li><a href="http://dev-houseofcases.co.uk/iphone-x-case">FAQ</a></li>
    <li><a href="http://dev-houseofcases.co.uk/iphone-x-case">SOL</a></li>
    <li><a href="http://dev-houseofcases.co.uk/iphone-x-case">ANPC</a></li>
</div>

<div class="social-links">
    <li><a href="https://www.facebook.com/casacuhuse.ro/"><span class="fa fa-facebook"></span></a></li>
    <li><a href="http://twitter.com/"><span class="fa fa-instagram"></span></a</li>
</div>

